default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.14  # Use the latest version
    hooks:
      - id: uv-lock
      - id: uv-sync
        args: ["--locked", "--all-packages"]

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.4
  hooks:
    - id: ruff
    - id: ruff-format
