from pydantic import BaseModel, Field


class PageMeta(BaseModel):
    page: int = Field(description="Current page")
    page_size: int = Field(description="Items requested per page")
    total_items: int = Field(description="Total items that can be queried")
    total_pages: int = Field(description="Total pages generated by total items divided by requested items")


class PageLink(BaseModel):
    next_page: str | None = Field(description="Next Page to be queried")
    prev_page: str | None = Field(description="Previous page, if any, that was queried")
    actual_page: str = Field(description="The actual page url that was queried")


class PageResult[T: BaseModel](BaseModel):
    items: list[T]
    links: PageLink
    meta: PageMeta
